name = "staffbase-mock-visualizer-ai-proxy"
main = "worker.js"
compatibility_date = "2026-05-04"
account_id = "55a5099eed6cfd6796a2ea7324c49a70"

[vars]
CLOUDFLARE_ACCOUNT_ID = "55a5099eed6cfd6796a2ea7324c49a70"
